# Используем официальный Python образ
FROM python:3.12-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем системные зависимости, включая инструменты сборки
RUN apt-get update && apt-get install -y \
    curl \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Обновляем pip, setuptools и wheel
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# Копируем и устанавливаем Python-зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Устанавливаем Python зависимости
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Копируем исходный код приложения
COPY . .

# Создаем директорию для медиа файлов
RUN mkdir -p media

# Создаем пользователя для безопасности
RUN adduser --disabled-password --gecos '' --shell /bin/bash app && \
    chown -R app:app /app
#USER app
USER root

# Открываем порт
EXPOSE 8000

# Добавляем healthcheck
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8000/api/health || exit 1

# Команда запуска
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]